# This manifest is used to deploy a single Kafka instance.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka  # The unique identifier of the deployment within the namespace.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka  # The label to match in order to select the pods managed by this deployment.
  template:
    metadata:
      labels:
        app: kafka  # The label applied to the pods.
    spec:
      containers:
      - name: kafka
        image: docker.io/bitnami/kafka:2.8.1
        ports:
        - containerPort: 9092  # The port which Kafka is listening on.
        env:
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
