# This file is used to create a service for the kafka pod

apiVersion: v1
kind: Service 
metadata:
  name: kafka-ui
spec:
  type: NodePort
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: 5000  # The port which the service is listening on.
      targetPort: 8080  # The port which the pods are listening on.
      nodePort: 30001
