apiVersion: batch/v1
kind: Job
metadata:
  name: job-py
spec:
  template:
    spec:
      containers:
      - name: job-py
        image: python:3.8.18-slim
        command: ["python", "-c", "print('hello pod')"]
      restartPolicy: OnFailure
