# This job will calculate pi to 2000 decimal places

apiVersion: batch/v1
kind: Job
metadata:
  name: pi # The name of the job uniquely identifies the job within the namespace.
spec:
  template:
    spec:
      containers:
      - name: pi  # The name of the container within the pod
        image: perl:5.34.0
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: OnFailure  # Possible values: Never, OnFailure
  backoffLimit: 4