apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
  - name: hello-pod
    image: ubuntu:20.04
    command: ["echo"]
    args: ["Hello World"]
  restartPolicy: Never  # possible values: Always, OnFailure, Never


# This manifests will create a pod that runs `echo "Hello World"`
